name: deploy_to_firebase_hosting

on:
  push:
    branches:
      - master

jobs:
  deploy_to_firebase_hosting:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@master
      - name: Setup nodejs
        uses: actions/setup-node@v1
      - name: Install dependencies
        run: npm install

      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
